In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\user\anaconda3\lib\site-packages (8.0.33)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\user\anaconda3\lib\site-packages (from mysql-connector-python) (3.20.3)

In [2]:
import mysql.connector

In [3]:
mydb = mysql.connector.connect(
        host = "localhost",
        user = "root",
        password = "",
        database = "ems"
)
#Function to add a new employee
    
def add_employee(emp_id,emp_name,emp_salary,emp_dept,email):
    
    #Create a cursor object
    cursor=mydb.cursor()
    
    #Execute the INSERT query
    
    query="INSERT INTO employee VALUES (%s ,%s ,%s, %s,%s)"
    values=(emp_id,emp_name,emp_salary,emp_dept,email)
    cursor.execute(query,values)
    
    #commit the changes to  the database
    mydb.commit()
    
    print("Employee added successfully")
    
    #Close the cursor object
    cursor.close()    

    
#Function to update a Existing employee
    
def update_employee(emp_id,emp_name,emp_salary,emp_dept,email):
    cursor=mydb.cursor()
    
    #Execute the UPDATE query

    
    query="UPDATE employee SET emp_name=%s,emp_salary=%s,emp_dept=%s,email=%s WHERE emp_id=%s"
    values=(emp_name,emp_salary,emp_dept,email,emp_id)

    cursor.execute(query,values)
    
    #commit the changes to  the database

    mydb.commit()
    
    print("Employee Updated successfully")
    
    cursor.close()   
    
#Function to update a Delete employee

    
def delete_employee(emp_id):
    cursor=mydb.cursor()
    
    #Execute the DELETE query

    
    query="DELETE from employee WHERE emp_id=%s"
    values=(emp_id,)
    
    cursor.execute(query,values)
    
    #commit the changes to  the database

    
    mydb.commit()
    
    print("Employee deleted successfully")
    
    cursor.close() 
    
#Function to list all employee


def list_all_employee():
    
    cursor=mydb.cursor()
    
    #Execute the select query

    query="SELECT * FROM employee"
    cursor.execute(query)
    rows=cursor.fetchall()

    for row in rows:
        print(row)

    cursor.close()
    
if __name__=="__main__":
    while True:
        print("Employee Management System")
        print("__________________________")
        print("1.Create New employee")
        print("2.Update Existing employee")
        print("3.Delete employee")
        print("4.List all employee")
        print("5.Exit")
        ch=int(input("Enter your choice"))
        if ch==1:
    
            emp_id=input("Enter id:")
            emp_name=input("Enter Name:")
            emp_salary=int(input("Enter Salary:"))
            emp_dept=input("Enter Department:")
            email=input("Enter email:")
        
            add_employee(emp_id,emp_name,emp_salary,emp_dept,email)
    
        elif ch==2:
    
            emp_id=int(input("Enter the employee id to update:"))
            
            emp_name=input("Enter Name:")
            emp_salary=int(input("Enter Salary:"))
            emp_dept=input("Enter Department:")
            email=input("Enter email:")
        
            update_employee(emp_id,emp_name,emp_salary,emp_dept,email)

        elif ch==3:
    
            emp_id=int(input("Enter the employee id to delete:"))
            
            
            delete_employee(emp_id)
            
        elif ch==4:
    
            list_all_employee()  
    
        elif ch==5:
            break; 

        else:
            print("Invalid choice.Plz try again")
    
    mydb.close()

Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice4
(1, 'JOHN DOE', Decimal('50000.00'), 'IT', 'SSS@GMAIL')
(2, 'JOHANA', Decimal('60000.00'), 'HR', 'ABC@GMAIL')
(3, 'JOBY', Decimal('15000.00'), 'ER', 'ABC@GMAIL')
(4, 'HARI', Decimal('65000.00'), 'IT', 'KKK@GMAIL')
(5, 'DEVI', Decimal('62000.00'), 'HR', 'ABC@GMAIL')
(7, 'jiji', Decimal('59000.00'), 'ece', 'jiji@gmail')
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice1
Enter id:6
Enter Name:jose
Enter Salary:44000
Enter Department:mech
Enter email:jose@gmail.com
Employee added successfully
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice4
(1, 'JOHN DOE', Decimal('50000.00'), 'IT', 'SSS@GMAIL')
(2, 'JOHANA', Decimal('60000.00'), 'HR', 'ABC@GMAIL')
(3, 'JOBY', Decimal('15000.00'), 'ER', 'ABC@GMAIL')
(4, 'HARI', Decimal('65000.00'), 'IT', 'KKK@GMAIL')
(5, 'DEVI', Decimal('62000.00'), 'HR', 'ABC@GMAIL')
(6, 'jose', Decimal('44000.00'), 'mech', 'jose@gmail')
(7, 'jiji', Decimal('59000.00'), 'ece', 'jiji@gmail')
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice2
Enter the employee id to update:3
Enter Name:jeni
Enter Salary:55000
Enter Department:cse
Enter email:jeni@gmail
Employee Updated successfully
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice4
(1, 'JOHN DOE', Decimal('50000.00'), 'IT', 'SSS@GMAIL')
(2, 'JOHANA', Decimal('60000.00'), 'HR', 'ABC@GMAIL')
(3, 'jeni', Decimal('55000.00'), 'cse', 'jeni@gmail')
(4, 'HARI', Decimal('65000.00'), 'IT', 'KKK@GMAIL')
(5, 'DEVI', Decimal('62000.00'), 'HR', 'ABC@GMAIL')
(6, 'jose', Decimal('44000.00'), 'mech', 'jose@gmail')
(7, 'jiji', Decimal('59000.00'), 'ece', 'jiji@gmail')
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice3
Enter the employee id to delete:5
Employee deleted successfully
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice4
(1, 'JOHN DOE', Decimal('50000.00'), 'IT', 'SSS@GMAIL')
(2, 'JOHANA', Decimal('60000.00'), 'HR', 'ABC@GMAIL')
(3, 'jeni', Decimal('55000.00'), 'cse', 'jeni@gmail')
(4, 'HARI', Decimal('65000.00'), 'IT', 'KKK@GMAIL')
(6, 'jose', Decimal('44000.00'), 'mech', 'jose@gmail')
(7, 'jiji', Decimal('59000.00'), 'ece', 'jiji@gmail')
Employee Management System
__________________________
1.Create New employee
2.Update Existing employee
3.Delete employee
4.List all employee
5.Exit
Enter your choice5